expressions:
  - fjällräven
  - humble bundle
  - japan
  - mcdonald
  - osaka
  - president's choice
  - starbucks
  - toms
  - tokyo
  - zojirushi
  - birkenstock
  - domino.?s
  - hario
  - mechanical(.*)key
  - mobile shop
  - optimum
  - pc points
  - raspberry pi
  - rw&co
  - 'rx.?5[6789]0'
  - steam
  - subway
  - uniqlo
  - airfryer
  - kicking horse
  - epic games
  - yubikey
  - yubico
  - sigma
  - soundcore
  - anker
  - gtx.16[56]0
