expressions:
  - nintendo switch
  - fjällräven
  - humble bundle
  - japan
  - mcDonald
  - nier automata
  - osaka
  - president's choice
  - starbucks
  - SteelSeries
  - toms
  - tokyo
  - zojirushi
  - birkenstock
  - domino.?s
  - fjallraven
  - hario
  - huggie
  - mechanical(.*)key
  - mobile shop
  - optimum
  - panasonic
  - pc points
  - raspberry pi
  - rw&co
  - 'rx.?5[6789]0'
  - steam
  - subway
  - uniqlo
  - airfryer
  - kicking horse
  - epic games
  - yubikey
  - yubico
  - sigma
  - chrome.?cast
  - soundcore
  - anker
