expressions:
  - fjällräven
  - humble bundle
  - japan
  - mcdonald
  - osaka
  - president's choice
  - starbucks
  - toms
  - tokyo
  - zojirushi
  - birkenstock
  - domino.?s
  - hario
  - mechanical(.*)key
  - koodo
  - optimum
  - pc points
  - raspberry pi
  - rw&co
  - steam
  - subway
  - uniqlo
  - airfryer
  - kicking horse
  - epic games
  - yubikey
  - yubico
  - sigma
  - soundcore
  - anker
  # graphics cards
  - gtx.?16[56]0
  - rx.?5[56789]
